name:                LPPaver
version:             0.0.3.1
github:              "rasheedja/LPPaver"
license:             MPL-2.0
author:              "Junaid Rasheed"
maintainer:          "rasheeja@aston.ac.uk"
copyright:           "MPL-2.0"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            An automated prover targeting problems that involve nonlinear real arithmetic
category:            Math, Maths, Mathematics, Formal methods, Theorem Provers, verification

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rasheedja/LPPaver#readme>

dependencies:
- base >= 4.7 && < 5
- mixed-types-num >= 0.5.10 && < 0.6
- aern2-mfun >= 0.2.9 && < 0.3
- aern2-mp >= 0.2.9.1 && < 0.3
- collect-errors >= 0.1 && < 0.2
- PropaFP >= 0.1.1 && < 0.2
- simplex-method >= 0.1 && < 0.2
- parallel >= 3.2 && < 3.3
- containers >= 0.6 && < 0.7
- pqueue >= 1.4 && < 1.5
- directory >= 1.3 && < 1.4
- optparse-applicative >= 0.16 && < 0.17

default-extensions:
- RebindableSyntax,
- ScopedTypeVariables,
- TypeFamilies,
- TypeOperators,
- ConstraintKinds,
- DefaultSignatures,
- MultiParamTypeClasses,
- FlexibleContexts,
- FlexibleInstances,
- UndecidableInstances

library:
  source-dirs: src

executables:
  lppaver:
    main: app/LPPaver.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -O2
    dependencies:
    - LPPaver
    - PropaFP
    - filepath

tests:
  LPPaver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - LPPaver
